import * as isolyGlobal from "."
import { isoly } from "."
import { TimeZone } from "./TimeZone"

describe("TimeZone", () => {
	it("Imports", () => {
		expect(isolyGlobal.TimeZone.is("Europe/Stockholm")).toBe(true)
		expect(isoly.TimeZone.is("Europe/Stockholm")).toBe(true)
		expect(TimeZone.is("Europe/Stockholm")).toBe(true)
	})
	it("Real timezones", () => {
		expect(TimeZone.is("Europe/Stockholm")).toBe(true)
		expect(TimeZone.is("Europe/London")).toBe(true)
		expect(TimeZone.is("Africa/Abidjan")).toBe(true)
		expect(TimeZone.is("Africa/Accra")).toBe(true)
		expect(TimeZone.is("Africa/Addis_Ababa")).toBe(true)
		expect(TimeZone.is("Africa/Algiers")).toBe(true)
		expect(TimeZone.is("Africa/Asmara")).toBe(true)
		expect(TimeZone.is("Africa/Bamako")).toBe(true)
		expect(TimeZone.is("Africa/Bangui")).toBe(true)
		expect(TimeZone.is("Africa/Banjul")).toBe(true)
		expect(TimeZone.is("Africa/Bissau")).toBe(true)
		expect(TimeZone.is("Africa/Blantyre")).toBe(true)
		expect(TimeZone.is("Africa/Brazzaville")).toBe(true)
		expect(TimeZone.is("Africa/Bujumbura")).toBe(true)
		expect(TimeZone.is("Africa/Cairo")).toBe(true)
		expect(TimeZone.is("Africa/Casablanca")).toBe(true)
		expect(TimeZone.is("Africa/Ceuta")).toBe(true)
		expect(TimeZone.is("Africa/Conakry")).toBe(true)
		expect(TimeZone.is("Africa/Dakar")).toBe(true)
		expect(TimeZone.is("Africa/Dar_es_Salaam")).toBe(true)
		expect(TimeZone.is("Africa/Djibouti")).toBe(true)
		expect(TimeZone.is("Africa/Douala")).toBe(true)
		expect(TimeZone.is("Africa/El_Aaiun")).toBe(true)
		expect(TimeZone.is("Africa/Freetown")).toBe(true)
		expect(TimeZone.is("Africa/Gaborone")).toBe(true)
		expect(TimeZone.is("Africa/Harare")).toBe(true)
		expect(TimeZone.is("Africa/Johannesburg")).toBe(true)
		expect(TimeZone.is("Africa/Juba")).toBe(true)
		expect(TimeZone.is("Africa/Kampala")).toBe(true)
		expect(TimeZone.is("Africa/Khartoum")).toBe(true)
		expect(TimeZone.is("Africa/Kigali")).toBe(true)
		expect(TimeZone.is("Africa/Kinshasa")).toBe(true)
		expect(TimeZone.is("Africa/Lagos")).toBe(true)
		expect(TimeZone.is("Africa/Libreville")).toBe(true)
		expect(TimeZone.is("Africa/Lome")).toBe(true)
		expect(TimeZone.is("Africa/Luanda")).toBe(true)
		expect(TimeZone.is("Africa/Lubumbashi")).toBe(true)
		expect(TimeZone.is("Africa/Lusaka")).toBe(true)
		expect(TimeZone.is("Africa/Malabo")).toBe(true)
		expect(TimeZone.is("Africa/Maputo")).toBe(true)
		expect(TimeZone.is("Africa/Maseru")).toBe(true)
		expect(TimeZone.is("Africa/Mbabane")).toBe(true)
		expect(TimeZone.is("Africa/Mogadishu")).toBe(true)
		expect(TimeZone.is("Africa/Monrovia")).toBe(true)
		expect(TimeZone.is("Africa/Nairobi")).toBe(true)
		expect(TimeZone.is("Africa/Ndjamena")).toBe(true)
		expect(TimeZone.is("Africa/Niamey")).toBe(true)
		expect(TimeZone.is("Africa/Nouakchott")).toBe(true)
		expect(TimeZone.is("Africa/Ouagadougou")).toBe(true)
		expect(TimeZone.is("Africa/Porto-Novo")).toBe(true)
		expect(TimeZone.is("Africa/Sao_Tome")).toBe(true)
		expect(TimeZone.is("Africa/Tripoli")).toBe(true)
		expect(TimeZone.is("Africa/Tunis")).toBe(true)
		expect(TimeZone.is("Africa/Windhoek")).toBe(true)
		expect(TimeZone.is("America/Adak")).toBe(true)
		expect(TimeZone.is("Pacific/Wallis")).toBe(true)
		expect(TimeZone.is("UTC")).toBe(true)
		expect(TimeZone.is("GMT")).toBe(true)
	})
	it("Flawed timezones", () => {
		expect(TimeZone.is("Europe/Göteborg")).toBe(false)
		expect(TimeZone.is("+01:00")).toBe(false)
		expect(TimeZone.is(undefined)).toBe(false)
		expect(TimeZone.is("timezone")).toBe(false)
		expect(TimeZone.is("TZ")).toBe(false)
		expect(TimeZone.is("Z")).toBe(false)
		expect(TimeZone.is("")).toBe(false)
	})
})
